// Reference-vector generator for the Rust port.
//
// Build in a developer command prompt (any MSVC install; no vcpkg, because
// everything it includes is header-only and dependency-free):
//
//   cl /nologo /std:c++latest /EHsc /W3 /O2 /I src tools\cpp_parity.cpp
//
// It prints the vectors that rust/crates/zzz-crypto/tests/cpp_parity.rs asserts
// against. That test is the parity gate: a transcription error in the EC2B
// tables, the MT19937-64 generator, the two pad byte orders or the .NET Random
// port shows up there as a failing assertion rather than as a wrong pad at
// runtime, where it would look like "the game changed something".

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

#include "crypto/crandom.hpp"
#include "crypto/ec2b.hpp"
#include "crypto/xorpad.hpp"

namespace {

uint64_t fnv1a(const uint8_t *data, size_t len) {
	uint64_t hash = 0xcbf29ce484222325ULL;
	for (size_t i = 0; i < len; i++) {
		hash ^= data[i];
		hash *= 0x100000001b3ULL;
	}
	return hash;
}

std::string hex(const uint8_t *data, size_t len) {
	static const char *digits = "0123456789ABCDEF";
	std::string out;
	for (size_t i = 0; i < len; i++) {
		out.push_back(digits[data[i] >> 4]);
		out.push_back(digits[data[i] & 0x0F]);
	}
	return out;
}

// The same 64-bit LCG the Rust test uses, so the two sides build identical
// synthetic EC2B blobs without sharing a fixture file.
uint64_t lcg(uint64_t &state) {
	state = state * 6364136223846793005ULL + 1442695040888963407ULL;
	return state;
}

std::vector<uint8_t> synthetic_blob(uint64_t keySeed, uint64_t payloadSeed) {
	std::vector<uint8_t> blob(28 + crypto::ec2b::seedSize, 0);
	// The magic is compared byte-reversed, so the wire bytes are literally "Ec2b".
	memcpy(blob.data(), "Ec2b", 4);
	uint32_t keySize = crypto::ec2b::keySize;
	memcpy(blob.data() + 4, &keySize, 4);
	uint64_t state = keySeed;
	for (size_t i = 0; i < crypto::ec2b::keySize; i += 8) {
		uint64_t word = lcg(state);
		memcpy(blob.data() + 8 + i, &word, 8);
	}
	uint32_t payloadSize = crypto::ec2b::seedSize;
	memcpy(blob.data() + 24, &payloadSize, 4);
	state = payloadSeed;
	for (size_t i = 0; i < crypto::ec2b::seedSize; i += 8) {
		uint64_t word = lcg(state);
		memcpy(blob.data() + 28 + i, &word, 8);
	}
	return blob;
}

void print_pad(const char *label, uint64_t seed, bool bigEndian) {
	auto pad = crypto::xorpad::generate(seed, bigEndian);
	printf("pad_%s %016llX %s %016llX\n", label,
		   static_cast<unsigned long long>(seed), hex(pad.data(), 32).c_str(),
		   static_cast<unsigned long long>(fnv1a(pad.data(), pad.size())));
}

void print_random(int32_t seed) {
	crypto::Random rng(seed);
	printf("random %d", seed);
	for (int i = 0; i < 8; i++) {
		printf(" %d", rng.next());
	}
	printf("\n");
	printf("client_rand_key %d %016llX\n", seed,
		   static_cast<unsigned long long>(crypto::clientRandKey(seed)));
}

} // namespace

int main() {
	printf("# generated by tools/cpp_parity.cpp\n");

	// Seeds: 0 and the published MT19937-64 seed 5489; the four region seeds from
	// assets/datamine.json; and the session key from a real captured login
	// (login_capture.json), which ties the fixture to live traffic.
	const uint64_t seeds[] = {
		0ULL,
		5489ULL,
		0x9543521FC9C8CAEDULL, // Europe
		0x20195BE788F21901ULL, // session_key from the 2026-09-21 capture
		0x1A7E69FE2F49590AULL, // Asia
		0x50C21982AC009AF2ULL, // America
		0x883B27204BF725D3ULL, // TW,HK,MO
	};
	for (uint64_t seed : seeds) {
		print_pad("region", seed, false);
		print_pad("session", seed, true);
	}

	// Int32.MinValue is included because the .NET generator treats it specially
	// (`Math.Abs` would overflow), and `crandom.hpp` branches on it.
	for (int32_t seed : {0, 1, -1, 123456789, 2147483647, INT32_MIN}) {
		print_random(seed);
	}

	printf("seed_from_seconds %lld %d\n", 0LL,
		   crypto::seedFromUnixSeconds(0));
	printf("seed_from_seconds %lld %d\n", 1789957600LL,
		   crypto::seedFromUnixSeconds(1789957600LL));
	printf("seed_from_seconds %lld %d\n", 1789957699LL,
		   crypto::seedFromUnixSeconds(1789957699LL));

	const uint64_t blobKeys[] = {0x1111111111111111ULL, 0ULL,
								 0xDEADBEEFCAFEBABEULL};
	const uint64_t blobPayloads[] = {0x2222222222222222ULL, 0ULL,
									 0x0123456789ABCDEFULL};
	for (size_t i = 0; i < 3; i++) {
		auto blob = synthetic_blob(blobKeys[i], blobPayloads[i]);
		printf("ec2b %016llX %016llX %016llX %016llX\n",
			   static_cast<unsigned long long>(blobKeys[i]),
			   static_cast<unsigned long long>(blobPayloads[i]),
			   static_cast<unsigned long long>(fnv1a(blob.data(), blob.size())),
			   static_cast<unsigned long long>(
				   crypto::ec2b::derive_seed(std::span<const uint8_t>(blob))));
	}

	return 0;
}
